-- Clipboard storage and capture. Image bytes live outside the JSON index.
return function(options)
	local C = { items = {} }
	local own_change = nil
	local image_dir = options.persistClipboard and (options.path .. ".images")
		or (hs.fs.temporaryDirectory() .. "launcher-clipboard-" .. hs.host.uuid())
	local MAX_IMAGE_BYTES = 32 * 1024 * 1024
	local MAX_TOTAL_IMAGE_BYTES = 256 * 1024 * 1024

	local function imagePath(item)
		-- Persisted filenames are content hashes, never arbitrary paths.
		if type(item.imageFile) == "string" and item.imageFile:match("^[a-f0-9]+%.png$") then
			return image_dir .. "/" .. item.imageFile
		end
	end
	C.imagePath = imagePath

	local function cleanupImages()
		if not hs.fs.attributes(image_dir) then
			return
		end
		local keep = {}
		for _, item in ipairs(C.items) do
			if item.imageFile then
				keep[item.imageFile] = true
			end
		end
		for name in hs.fs.dir(image_dir) do
			if name:match("^[a-f0-9]+%.png$") and not keep[name] then
				os.remove(image_dir .. "/" .. name)
			end
		end
	end

	local function persist()
		if not options.persistClipboard then
			cleanupImages()
			return true
		end
		local records = {}
		for i, item in ipairs(C.items) do
			records[i] = {
				type = item.type,
				text = item.text,
				createdAt = item.createdAt,
				source = item.source,
				sourceBundleId = item.sourceBundleId,
				imageFile = item.imageFile,
				imageBytes = item.imageBytes,
				width = item.width,
				height = item.height,
			}
		end
		local encoded = hs.json.encode(records, true)
		local file = io.open(options.path .. ".tmp", "w")
		if not file then
			return false
		end
		local written = file:write(encoded)
		local closed = file:close()
		if not written or not closed or not os.rename(options.path .. ".tmp", options.path) then
			return false
		end
		cleanupImages()
		return true
	end

	local function trimHistory()
		while #C.items > options.maxClipboardItems do
			table.remove(C.items)
		end
		local bytes = 0
		for i = #C.items, 1, -1 do
			bytes = bytes + (C.items[i].imageBytes or 0)
		end
		for i = #C.items, 1, -1 do
			if bytes <= MAX_TOTAL_IMAGE_BYTES then
				break
			end
			if C.items[i].type == "image" then
				bytes = bytes - (C.items[i].imageBytes or 0)
				table.remove(C.items, i)
			end
		end
	end

	function C.load()
		if not options.persistClipboard then
			return
		end
		local file = io.open(options.path, "r")
		if not file then
			return
		end
		local ok, data = pcall(hs.json.decode, file:read("*all"))
		file:close()
		if not ok or type(data) ~= "table" then
			return
		end
		for _, item in ipairs(data) do
			if type(item) == "table" and type(item.text) == "string" then
				if item.type == "image" then
					local path = imagePath(item)
					local attrs = path and hs.fs.attributes(path)
					if attrs and attrs.mode == "file" then
						item.imageBytes = attrs.size
						table.insert(C.items, item)
					end
				elseif item.text ~= "" then
					item.type = "text"
					table.insert(C.items, item)
				end
			end
		end
		trimHistory()
		for _, item in ipairs(C.items) do
			item._searchTitleLower = (item.text .. " " .. (item.source or "")):lower()
		end
	end

	local function sourceInfo()
		local bundleId = hs.pasteboard.readDataForUTI("org.nspasteboard.source")
		local front = hs.application.frontmostApplication()
		if not bundleId or bundleId == "" then
			bundleId = front and front:bundleID()
		end
		local name = bundleId and hs.application.nameForBundleID(bundleId)
		return name or (front and front:name()), bundleId
	end

	function C.capture(text)
		if hs.pasteboard.changeCount() == own_change then
			return false
		end
		-- Respect standard sensitive/transient clipboard markers, not just app names.
		for _, uti in ipairs(hs.pasteboard.contentTypes() or {}) do
			if
				uti == "org.nspasteboard.ConcealedType"
				or uti == "org.nspasteboard.TransientType"
				or uti == "org.nspasteboard.AutoGeneratedType"
			then
				return false
			end
		end
		local source, bundleId = sourceInfo()
		for _, ignored in ipairs(options.ignoredClipboardBundleIds or {}) do
			if ignored == bundleId then
				return false
			end
		end

		local item = { createdAt = os.time(), source = source, sourceBundleId = bundleId }
		local image = hs.pasteboard.readImage()
		if image then
			local url = image:encodeAsURLString(true, "PNG")
			local encoded = url and url:match("base64,(.*)$")
			if not encoded or #encoded > MAX_IMAGE_BYTES * 4 / 3 + 4 then
				return false
			end
			local bytes = hs.base64.decode(encoded)
			if not bytes or #bytes > MAX_IMAGE_BYTES then
				return false
			end
			item.type = "image"
			item.imageFile = hs.hash.SHA256(bytes) .. ".png"
			item.imageBytes = #bytes
			local size = image:size()
			item.width, item.height = math.floor(size.w), math.floor(size.h)
			item.text = "Image · " .. item.width .. " × " .. item.height
			if type(text) == "string" and text:match("^/[^\n]+%.[%w]+$") then
				item.text = text:match("([^/]+)$") or item.text
			end
			if not hs.fs.attributes(image_dir) and not hs.fs.mkdir(image_dir) then
				return false
			end
			if hs.fs.attributes(image_dir, "permissions") ~= "rwx------" then
				local _, ok = hs.execute("/bin/chmod 700 " .. "'" .. image_dir:gsub("'", "'\\''") .. "'")
				if not ok then
					return false
				end
			end
			local file = io.open(imagePath(item), "wb")
			if not file then
				return false
			end
			local written = file:write(bytes)
			local closed = file:close()
			if not written or not closed then
				return false
			end
		elseif type(text) == "string" and text ~= "" and #text <= options.maxClipboardChars then
			item.type, item.text = "text", text
		else
			return false
		end

		for i = #C.items, 1, -1 do
			local old = C.items[i]
			if
				(item.type == "image" and old.imageFile == item.imageFile)
				or (item.type == "text" and old.type ~= "image" and old.text == item.text)
			then
				table.remove(C.items, i)
			end
		end
		item._searchTitleLower = (item.text .. " " .. (item.source or "")):lower()
		table.insert(C.items, 1, item)
		trimHistory()
		if not persist() then
			options.notify("Launcher", "Could not save clipboard history")
		end
		return true
	end

	function C.write(item)
		local ok
		if item.type == "image" then
			local path = imagePath(item)
			local image = path and hs.image.imageFromPath(path)
			ok = image and hs.pasteboard.writeObjects(image)
		else
			ok = hs.pasteboard.setContents(item.text)
		end
		if ok then
			own_change = hs.pasteboard.changeCount()
		end
		return ok == true
	end

	function C.clear()
		for i = #C.items, 1, -1 do
			C.items[i] = nil
		end
		if not persist() then
			options.notify("Launcher", "Could not clear saved clipboard history")
		end
	end

	function C.stop()
		if not options.persistClipboard then
			C.clear()
			hs.fs.rmdir(image_dir)
		end
	end

	return C
end
